Iter15
sergeizaitcev/metrics pull request #15
Opened 2023-10-25 19:15 UTC by sergeizaitcev

2023-11-04 06:47 UTC, s-shpak requested changes
Поправь несколько замечаний, а потом обсудим worker pool

2023-11-04 06:47 UTC, s-shpak commented on cmd/agent/main.go
> +		ReportInterval: time.Duration(flagReportInterval) * time.Second,
Лучше правильный Duration высчитывать при получении конфига, т.к. если в будущем секунды поменяются на, например, миллисекунду, то нам надо будет незабыть поправить рассчет во всех местах, где эти значения используются

2023-11-04 06:47 UTC, s-shpak commented on cmd/server/main.go
> +	if pg, ok := storage.(*postgres.Storage); ok {
Это лучше перенести в логику инициализации хендлера к БД. Тогда проверку не надо будет делать

2023-11-04 06:47 UTC, s-shpak commented on internal/agent/agent.go
> +						return err
Если сервер не доступен по какой-то причние, то это не должно завершать выполнение всего пула воркеров. Здесь ошибка должна либо быть действительно критической, либо не надо использовать `errgroup`, а надо просто логировать ошибку и продолжать выполнение.

Думаю, что второй вариант лучше

2023-11-04 06:47 UTC, s-shpak commented on internal/agent/agent.go
> +	req.Header.Add("Accept-Encoding", "gzip")
Агент также должен сжимать запрос

2023-11-05 07:53 UTC, sergeizaitcev commented on cmd/agent/main.go
> +		ReportInterval: time.Duration(flagReportInterval) * time.Second,
Готово.

2023-11-05 07:54 UTC, sergeizaitcev commented on cmd/server/main.go
> +	if pg, ok := storage.(*postgres.Storage); ok {
Готово.

2023-11-05 07:54 UTC, sergeizaitcev commented on internal/agent/agent.go
> +						return err
Готово.

2023-11-05 07:54 UTC, sergeizaitcev commented on internal/agent/agent.go
> +	req.Header.Add("Accept-Encoding", "gzip")
Готово.

2023-11-05 18:30 UTC, s-shpak requested changes

2023-11-05 18:30 UTC, s-shpak commented on internal/agent/agent.go
> +			case <-pollChan:
Это не очень удобно: в идеале пользователь канала должен либо читать из него, либо в него писать. Так каналами легче управлять. Что хотелось бы видеть: сборщик метрик раз в свой интервал посылает метрики в канал, не блокируется. Если свободного воркера нет, то метрика дропается. Если есть, то отправляется на сервер. Подумай, как это сделать

2023-11-05 18:30 UTC, s-shpak commented on internal/agent/agent.go
> +	snapshotChan := make(chan []metrics.Metric)
Кажется неправильным, что канал здесь небуферизован: его емкость должна быть равна количеству воркеров. Но мы не знаем количество воркеров в этой функции. Как решить эту проблему?

2023-11-05 18:30 UTC, s-shpak commented on internal/agent/agent.go
> +	wg.Add(a.config.RateLimit)
Если количество воркеров поменяется, а мы забудем это поправить здесь, то мы уйдем в дедлок при завершении программы. Это надо исправить

2023-11-05 18:30 UTC, s-shpak commented on internal/server/server.go
> +	s.storage, err = storage.NewStorage(config.Storage)
Соединение с БД также надо корректно закрывать при graceful shutdown. Поэтому лучше вынести graceful shutdown отдельно. Можно посмотреть, как я предлагал это делать на одном из вебинаров: https://github.com/s-shpak/webinar-goroutines#контекст-и-graceful-shutdown

2023-11-05 19:44 UTC, sergeizaitcev commented on internal/agent/agent.go
> +			case <-pollChan:
Готово.

2023-11-05 19:44 UTC, sergeizaitcev commented on internal/agent/agent.go
> +	snapshotChan := make(chan []metrics.Metric)
Готово.

2023-11-05 19:44 UTC, sergeizaitcev commented on internal/agent/agent.go
> +	wg.Add(a.config.RateLimit)
Готово.

2023-11-05 19:44 UTC, sergeizaitcev commented on internal/server/server.go
> +	s.storage, err = storage.NewStorage(config.Storage)
Готово.

2023-11-07 12:53 UTC, s-shpak approved these changes

2023-11-07 13:06 UTC, merged