Iter20
sergeizaitcev/metrics pull request #19
Opened 2024-01-10 10:48 UTC by sergeizaitcev

2024-01-10 14:38 UTC, gonozov0 requested changes
Отличная работа 👍
Добавил пару комментариев по улучшению кода

2024-01-10 14:38 UTC, gonozov0 commented on version/version.go
> +}
На мой взгляд переусложнил, PrintTo нигде не используется больше, да и надобности нету. Если следовать принципу YAGNI, то стоит просто вызвать fmt.Println в Print, но не настаиваю

2024-01-10 14:38 UTC, gonozov0 commented on makefile
> +	@$(GO_BUILD) -o ./cmd/agent/agent ./cmd/agent
Добавь выше в lint дополнительно команду вызова своего нового анализатора staticlint

2024-01-11 07:28 UTC, sergeizaitcev commented on version/version.go
> +}
Готово.

2024-01-11 07:28 UTC, sergeizaitcev commented on makefile
> +	@$(GO_BUILD) -o ./cmd/agent/agent ./cmd/agent
Готово.

2024-01-11 14:37 UTC, gonozov0 approved these changes
Работа прекрасно выполнена и зачтена 👍

2024-01-11 14:42 UTC, merged